### ISSUE TITLE
Fix tests.

### ISSUE THREAD

**Issue by Zerg1996** [BoostCMake/pool#1]
Tests with include pool.hpp can't find file memcheck.h
```
#ifdef BOOST_POOL_VALGRIND
#include <set>
#include <valgrind/memcheck.h>
#endif
```

**Comment by Nemo1369** [comment]
It means no Valgrind was installed, or no check for Valgrind is performed so no definition of BOOST_POOL_VALGRIND was provided.

**Comment by Zerg1996** [comment]
So okey, I fix it with checking availability Valgrind.
